### PR TITLE
added three entries

### PR DESCRIPTION
**Pull request by peterstadler**
- WeGA
- SMuFL-Browser
- TEI Roma

### CODE REVIEW

**Comment by joewiz** [comment]
Thanks, Peter!

**Comment by joewiz** [comment]
I didn't realize Roma ran on eXist - cool!

**Comment by peterstadler** [comment]
Yes, but a very old one (as is the current Roma interface).
There are plans to replace Roma (see https://github.com/sebastianrahtz/Byzantium) in the future and subsequently get rid of the exist-db backend. But so far it's just running and running …

**Comment by joewiz** [comment]
Good old Roma!

**Pull request merged**
